import LoginBgImg1 from "./login-bg-img1.png"
import LoginBg from "./login-bg.png"
import Loading from "./loading-white.png"
import Loading2 from "./loading2.png"
import Logo from "./Logo.svg"
import MarkJohn from "./MarkJohn.png"
import BirbaloHome from "./BirbaloHomeImg.png"
import OrdersOwerview from "./OrdersOwerview.png"
import Referral from "./Referral.png"
import SalesOwerview from "./SalesOwerview.png"
import Satisfaction from "./Satisfaction.png"
import UsersHome from "./UsersHome.png"
import AuthorsImg1 from "./AuthorsImg1.svg"
import AuthorsImg2 from "./AuthorsImg2.svg"
import AuthorsImg3 from "./AuthorsImg3.svg"
import AuthorsImg4 from "./AuthorsImg4.svg"
import AuthorsImg5 from "./AuthorsImg5.svg"
import AuthorsImg6 from "./AuthorsImg6.svg"
import NavbarDocumentation from "./NavbarImgDocumentation.png"
import ProjectImg1 from "./ProjectsImg1.svg"
import ProjectImg2 from "./ProjectsImg2.svg"
import ProjectImg3 from "./ProjectsImg3.svg"
import ProjectImg4 from "./ProjectsImg4.svg"
import ProjectImg5 from "./ProjectsImg5.svg"

export {LoginBg, LoginBgImg1, Loading, Loading2, Logo, MarkJohn, BirbaloHome, OrdersOwerview, Referral, SalesOwerview, Satisfaction, UsersHome, AuthorsImg1, AuthorsImg2, AuthorsImg3, AuthorsImg4,AuthorsImg5,AuthorsImg6, NavbarDocumentation, ProjectImg1, ProjectImg2, ProjectImg3, ProjectImg4,ProjectImg5}